// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ExploreSearchConceptChildrenOKCode is the HTTP code returned for type ExploreSearchConceptChildrenOK
const ExploreSearchConceptChildrenOKCode int = 200

/*ExploreSearchConceptChildrenOK MedCo-Explore search concept children query response.

swagger:response exploreSearchConceptChildrenOK
*/
type ExploreSearchConceptChildrenOK struct {

	/*
	  In: Body
	*/
	Payload *ExploreSearchConceptChildrenOKBody `json:"body,omitempty"`
}

// NewExploreSearchConceptChildrenOK creates ExploreSearchConceptChildrenOK with default headers values
func NewExploreSearchConceptChildrenOK() *ExploreSearchConceptChildrenOK {

	return &ExploreSearchConceptChildrenOK{}
}

// WithPayload adds the payload to the explore search concept children o k response
func (o *ExploreSearchConceptChildrenOK) WithPayload(payload *ExploreSearchConceptChildrenOKBody) *ExploreSearchConceptChildrenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore search concept children o k response
func (o *ExploreSearchConceptChildrenOK) SetPayload(payload *ExploreSearchConceptChildrenOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreSearchConceptChildrenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ExploreSearchConceptChildrenDefault Error response.

swagger:response exploreSearchConceptChildrenDefault
*/
type ExploreSearchConceptChildrenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *ExploreSearchConceptChildrenDefaultBody `json:"body,omitempty"`
}

// NewExploreSearchConceptChildrenDefault creates ExploreSearchConceptChildrenDefault with default headers values
func NewExploreSearchConceptChildrenDefault(code int) *ExploreSearchConceptChildrenDefault {
	if code <= 0 {
		code = 500
	}

	return &ExploreSearchConceptChildrenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the explore search concept children default response
func (o *ExploreSearchConceptChildrenDefault) WithStatusCode(code int) *ExploreSearchConceptChildrenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the explore search concept children default response
func (o *ExploreSearchConceptChildrenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the explore search concept children default response
func (o *ExploreSearchConceptChildrenDefault) WithPayload(payload *ExploreSearchConceptChildrenDefaultBody) *ExploreSearchConceptChildrenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore search concept children default response
func (o *ExploreSearchConceptChildrenDefault) SetPayload(payload *ExploreSearchConceptChildrenDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreSearchConceptChildrenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
