// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetCohortsParams creates a new GetCohortsParams object
// no default values defined in spec.
func NewGetCohortsParams() GetCohortsParams {

	return GetCohortsParams{}
}

// GetCohortsParams contains all the bound params for the get cohorts operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCohorts
type GetCohortsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCohortsParams() beforehand.
func (o *GetCohortsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
