// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ldsec/medco/connector/restapi/models"
)

// GetCohortsHandlerFunc turns a function with the right signature into a get cohorts handler
type GetCohortsHandlerFunc func(GetCohortsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCohortsHandlerFunc) Handle(params GetCohortsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetCohortsHandler interface for that can handle valid get cohorts params
type GetCohortsHandler interface {
	Handle(GetCohortsParams, *models.User) middleware.Responder
}

// NewGetCohorts creates a new http.Handler for the get cohorts operation
func NewGetCohorts(ctx *middleware.Context, handler GetCohortsHandler) *GetCohorts {
	return &GetCohorts{Context: ctx, Handler: handler}
}

/*GetCohorts swagger:route GET /node/explore/cohorts medco-node getCohorts

Retrieve cohort names and patient set IDs

*/
type GetCohorts struct {
	Context *middleware.Context
	Handler GetCohortsHandler
}

func (o *GetCohorts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCohortsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetCohortsDefaultBody get cohorts default body
//
// swagger:model GetCohortsDefaultBody
type GetCohortsDefaultBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get cohorts default body
func (o *GetCohortsDefaultBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCohortsDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCohortsDefaultBody) UnmarshalBinary(b []byte) error {
	var res GetCohortsDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetCohortsOKBodyItems0 get cohorts o k body items0
//
// swagger:model GetCohortsOKBodyItems0
type GetCohortsOKBodyItems0 struct {

	// cohort Id
	CohortID int64 `json:"cohortId,omitempty"`

	// cohort name
	CohortName string `json:"cohortName,omitempty"`

	// creation date
	CreationDate string `json:"creationDate,omitempty"`

	// query definition
	QueryDefinition *GetCohortsOKBodyItems0QueryDefinition `json:"queryDefinition,omitempty"`

	// query Id
	QueryID int64 `json:"queryId,omitempty"`

	// update date
	UpdateDate string `json:"updateDate,omitempty"`
}

// Validate validates this get cohorts o k body items0
func (o *GetCohortsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateQueryDefinition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCohortsOKBodyItems0) validateQueryDefinition(formats strfmt.Registry) error {

	if swag.IsZero(o.QueryDefinition) { // not required
		return nil
	}

	if o.QueryDefinition != nil {
		if err := o.QueryDefinition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("queryDefinition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCohortsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCohortsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetCohortsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetCohortsOKBodyItems0QueryDefinition get cohorts o k body items0 query definition
//
// swagger:model GetCohortsOKBodyItems0QueryDefinition
type GetCohortsOKBodyItems0QueryDefinition struct {

	// query timing
	QueryTiming models.Timing `json:"queryTiming,omitempty"`

	// query timing sequence
	QueryTimingSequence []*models.TimingSequenceInfo `json:"queryTimingSequence"`

	// selection panels
	SelectionPanels []*models.Panel `json:"selectionPanels"`

	// sequential panels
	SequentialPanels []*models.Panel `json:"sequentialPanels"`
}

// Validate validates this get cohorts o k body items0 query definition
func (o *GetCohortsOKBodyItems0QueryDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateQueryTiming(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateQueryTimingSequence(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSelectionPanels(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSequentialPanels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCohortsOKBodyItems0QueryDefinition) validateQueryTiming(formats strfmt.Registry) error {

	if swag.IsZero(o.QueryTiming) { // not required
		return nil
	}

	if err := o.QueryTiming.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("queryDefinition" + "." + "queryTiming")
		}
		return err
	}

	return nil
}

func (o *GetCohortsOKBodyItems0QueryDefinition) validateQueryTimingSequence(formats strfmt.Registry) error {

	if swag.IsZero(o.QueryTimingSequence) { // not required
		return nil
	}

	for i := 0; i < len(o.QueryTimingSequence); i++ {
		if swag.IsZero(o.QueryTimingSequence[i]) { // not required
			continue
		}

		if o.QueryTimingSequence[i] != nil {
			if err := o.QueryTimingSequence[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryDefinition" + "." + "queryTimingSequence" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCohortsOKBodyItems0QueryDefinition) validateSelectionPanels(formats strfmt.Registry) error {

	if swag.IsZero(o.SelectionPanels) { // not required
		return nil
	}

	for i := 0; i < len(o.SelectionPanels); i++ {
		if swag.IsZero(o.SelectionPanels[i]) { // not required
			continue
		}

		if o.SelectionPanels[i] != nil {
			if err := o.SelectionPanels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryDefinition" + "." + "selectionPanels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetCohortsOKBodyItems0QueryDefinition) validateSequentialPanels(formats strfmt.Registry) error {

	if swag.IsZero(o.SequentialPanels) { // not required
		return nil
	}

	for i := 0; i < len(o.SequentialPanels); i++ {
		if swag.IsZero(o.SequentialPanels[i]) { // not required
			continue
		}

		if o.SequentialPanels[i] != nil {
			if err := o.SequentialPanels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryDefinition" + "." + "sequentialPanels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCohortsOKBodyItems0QueryDefinition) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCohortsOKBodyItems0QueryDefinition) UnmarshalBinary(b []byte) error {
	var res GetCohortsOKBodyItems0QueryDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
