// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetExploreQueryParams creates a new GetExploreQueryParams object
//
// There are no default values defined in the spec.
func NewGetExploreQueryParams() GetExploreQueryParams {

	return GetExploreQueryParams{}
}

// GetExploreQueryParams contains all the bound params for the get explore query operation
// typically these are obtained from a http.Request
//
// swagger:parameters getExploreQuery
type GetExploreQueryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Query ID
	  Required: true
	  In: path
	*/
	QueryID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetExploreQueryParams() beforehand.
func (o *GetExploreQueryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rQueryID, rhkQueryID, _ := route.Params.GetOK("queryId")
	if err := o.bindQueryID(rQueryID, rhkQueryID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindQueryID binds and validates parameter QueryID from path.
func (o *GetExploreQueryParams) bindQueryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.QueryID = raw

	return nil
}
