#!/usr/bin/env bash
set -Eeuo pipefail

### script to download the MedCo example datasets

SCRIPT_FOLDER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $SCRIPT_FOLDER
REPO_URL="https://github.com/ldsec/projects-data/blob/master/medco/datasets"
DATASET="${1-}"

if [[ "$DATASET" = "genomic_orig" ]]; then
  # genomic (v0) dataset
  mkdir -p ${SCRIPT_FOLDER}/genomic/tcga_cbio/
  wget -O ${SCRIPT_FOLDER}/genomic/tcga_cbio/mutation_data.csv ${REPO_URL}/genomic/tcga_cbio/mutation_data.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/genomic/tcga_cbio/clinical_data.csv ${REPO_URL}/genomic/tcga_cbio/clinical_data.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/genomic/sensitive.txt ${REPO_URL}/genomic/sensitive.txt?raw=true
elif [[ "$DATASET" = "genomic_fake" ]]; then
  # genomic (v0) dataset
  mkdir -p ${SCRIPT_FOLDER}/genomic/tcga_cbio/
  wget -O ${SCRIPT_FOLDER}/genomic/tcga_cbio/mutation_data_fake.csv ${REPO_URL}/genomic/tcga_cbio/mutation_data_fake.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/genomic/tcga_cbio/clinical_data_fake.csv ${REPO_URL}/genomic/tcga_cbio/clinical_data_fake.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/genomic/sensitive.txt ${REPO_URL}/genomic/sensitive.txt?raw=true
elif [[ "$DATASET" = "genomic_small" ]]; then
  # genomic (v0) dataset
  mkdir -p ${SCRIPT_FOLDER}/genomic/tcga_cbio/
  wget -O ${SCRIPT_FOLDER}/genomic/tcga_cbio/8_mutation_data.csv ${REPO_URL}/genomic/tcga_cbio/8_mutation_data.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/genomic/tcga_cbio/8_clinical_data.csv ${REPO_URL}/genomic/tcga_cbio/8_clinical_data.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/genomic/sensitive.txt ${REPO_URL}/genomic/sensitive.txt?raw=true
elif [[ "$DATASET" = "i2b2" ]]; then
  # i2b2 demo (v1) dataset
  mkdir -p ${SCRIPT_FOLDER}/i2b2/original/
  mkdir -p ${SCRIPT_FOLDER}/i2b2/converted/
  wget -O ${SCRIPT_FOLDER}/i2b2/original/birn.csv ${REPO_URL}/i2b2/original/birn.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/concept_dimension.csv ${REPO_URL}/i2b2/original/concept_dimension.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/custom_meta.csv ${REPO_URL}/i2b2/original/custom_meta.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/dummy_to_patient.csv ${REPO_URL}/i2b2/original/dummy_to_patient.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/i2b2.csv ${REPO_URL}/i2b2/original/i2b2.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/icd10_icd9.csv ${REPO_URL}/i2b2/original/icd10_icd9.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/observation_fact.csv ${REPO_URL}/i2b2/original/observation_fact.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/patient_dimension.csv ${REPO_URL}/i2b2/original/patient_dimension.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/table_access.csv ${REPO_URL}/i2b2/original/table_access.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/visit_dimension.csv ${REPO_URL}/i2b2/original/visit_dimension.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/concept_dimension.csv ${REPO_URL}/i2b2/original/concept_dimension.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/original/modifier_dimension.csv ${REPO_URL}/i2b2/original/modifier_dimension.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/sensitive.txt ${REPO_URL}/i2b2/sensitive.txt?raw=true
  wget -O ${SCRIPT_FOLDER}/i2b2/files.toml ${REPO_URL}/i2b2/files.toml?raw=true
elif [[ "$DATASET" = "spo_synthetic" ]]; then
  # SPO synthetic dataset generated by the RDF loader
  mkdir -p ${SCRIPT_FOLDER}/spo-synthetic/
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/CONCEPT_DIMENSION.csv ${REPO_URL}/spo-synthetic/CONCEPT_DIMENSION.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/MODIFIER_DIMENSION.csv ${REPO_URL}/spo-synthetic/MODIFIER_DIMENSION.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/observation_fact_spo.csv ${REPO_URL}/spo-synthetic/observation_fact_spo.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/PATIENT_DIMENSION.csv ${REPO_URL}/spo-synthetic/PATIENT_DIMENSION.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/PROVIDER_DIMENSION.csv ${REPO_URL}/spo-synthetic/PROVIDER_DIMENSION.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/spo_onto_db.csv ${REPO_URL}/spo-synthetic/spo_onto_db.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/table_access_clean.csv ${REPO_URL}/spo-synthetic/table_access_clean.csv?raw=true
  wget -O ${SCRIPT_FOLDER}/spo-synthetic/VISIT_DIMENSION.csv ${REPO_URL}/spo-synthetic/VISIT_DIMENSION.csv?raw=true
else
  echo "invalid download ID: [genomic_orig|genomic_fake|genomic_small|i2b2|spo_synthetic]"
  exit 1
fi
