version: '2.4'
services:
  medco-cli-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-cli-client
    environment:
      - MEDCO_NODE_IDX=${MEDCO_NODE_IDX:?}
      - MEDCO_CONNECTOR_URL=https://${MEDCO_NODE_DNS_NAME}/medco
      - OIDC_REQ_TOKEN_URL=https://${MEDCO_NODE_DNS_NAME:?}/auth/realms/${KEYCLOAK_REALM:?}/protocol/openid-connect/token
      - OIDC_REQ_TOKEN_CLIENT_ID=${KEYCLOAK_CLIENT_ID:?}
    volumes:
      - ./configuration:/medco-configuration

  medco-loader:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - MEDCO_NODE_IDX=${MEDCO_NODE_IDX:?}
      - I2B2_DB_HOST=${MEDCO_NODE_DNS_NAME:?}
      - MC_DB_HOST=${MEDCO_NODE_DNS_NAME:?}
    volumes:
      - ./configuration:/medco-configuration
