// Code generated by go-swagger; DO NOT EDIT.

package survival_analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSurvivalAnalysisOKCode is the HTTP code returned for type GetSurvivalAnalysisOK
const GetSurvivalAnalysisOKCode int = 200

/*GetSurvivalAnalysisOK Queried survival analysis

swagger:response getSurvivalAnalysisOK
*/
type GetSurvivalAnalysisOK struct {

	/*
	  In: Body
	*/
	Payload *GetSurvivalAnalysisOKBody `json:"body,omitempty"`
}

// NewGetSurvivalAnalysisOK creates GetSurvivalAnalysisOK with default headers values
func NewGetSurvivalAnalysisOK() *GetSurvivalAnalysisOK {

	return &GetSurvivalAnalysisOK{}
}

// WithPayload adds the payload to the get survival analysis o k response
func (o *GetSurvivalAnalysisOK) WithPayload(payload *GetSurvivalAnalysisOKBody) *GetSurvivalAnalysisOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get survival analysis o k response
func (o *GetSurvivalAnalysisOK) SetPayload(payload *GetSurvivalAnalysisOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSurvivalAnalysisOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSurvivalAnalysisNotFoundCode is the HTTP code returned for type GetSurvivalAnalysisNotFound
const GetSurvivalAnalysisNotFoundCode int = 404

/*GetSurvivalAnalysisNotFound TODO not found

swagger:response getSurvivalAnalysisNotFound
*/
type GetSurvivalAnalysisNotFound struct {
}

// NewGetSurvivalAnalysisNotFound creates GetSurvivalAnalysisNotFound with default headers values
func NewGetSurvivalAnalysisNotFound() *GetSurvivalAnalysisNotFound {

	return &GetSurvivalAnalysisNotFound{}
}

// WriteResponse to the client
func (o *GetSurvivalAnalysisNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*GetSurvivalAnalysisDefault Error response.

swagger:response getSurvivalAnalysisDefault
*/
type GetSurvivalAnalysisDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *GetSurvivalAnalysisDefaultBody `json:"body,omitempty"`
}

// NewGetSurvivalAnalysisDefault creates GetSurvivalAnalysisDefault with default headers values
func NewGetSurvivalAnalysisDefault(code int) *GetSurvivalAnalysisDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSurvivalAnalysisDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get survival analysis default response
func (o *GetSurvivalAnalysisDefault) WithStatusCode(code int) *GetSurvivalAnalysisDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get survival analysis default response
func (o *GetSurvivalAnalysisDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get survival analysis default response
func (o *GetSurvivalAnalysisDefault) WithPayload(payload *GetSurvivalAnalysisDefaultBody) *GetSurvivalAnalysisDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get survival analysis default response
func (o *GetSurvivalAnalysisDefault) SetPayload(payload *GetSurvivalAnalysisDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSurvivalAnalysisDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
