// Code generated by go-swagger; DO NOT EDIT.

package genomic_annotations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new genomic annotations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for genomic annotations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetValues gets genomic annotations values
*/
func (a *Client) GetValues(params *GetValuesParams, authInfo runtime.ClientAuthInfoWriter) (*GetValuesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetValuesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getValues",
		Method:             "GET",
		PathPattern:        "/genomic-annotations/{annotation}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetValuesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetValuesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetValuesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetVariants gets variants corresponding to a genomic annotation value
*/
func (a *Client) GetVariants(params *GetVariantsParams, authInfo runtime.ClientAuthInfoWriter) (*GetVariantsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetVariantsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getVariants",
		Method:             "GET",
		PathPattern:        "/genomic-annotations/{annotation}/{value}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetVariantsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetVariantsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetVariantsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
