version: "2.4"
services:
  i2b2-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - I2B2_DB_NAME=i2b2medcosrv0
      - I2B2_DOMAIN_NAME=i2b2medcosrv0
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8090:8080"
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.100

  medco-unlynx-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    environment:
      - MEDCO_NODE_IDX=0
      - UNLYNX_DEBUG_LEVEL=3
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.101
    volumes:
      - ./configuration:/medco-configuration

  medco-unlynx-wstunnel-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx-wstunnel
    environment:
      - SERVER_LISTEN_URL=ws://0.0.0.0:2003
      - SERVER_DEST_ADDRESS=medco-unlynx-srv0:2001
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.103
    volumes:
      - ./configuration:/medco-configuration

  medco-connector-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    ports:
      - "1990:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv0:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv0
      - I2B2_LOGIN_USER=e2etest
      - I2B2_LOGIN_PASSWORD=e2etest
      - LOG_LEVEL=5
      - MEDCO_NODE_IDX=0
      - MC_DB_NAME=medcoconnectorsrv0
      - I2B2_DB_NAME=i2b2medcosrv0
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.102
    volumes:
      - ./configuration:/medco-configuration

  nginx:
    extends:
      file: ../docker-compose-definitions.yml
      service: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.200

  i2b2-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - I2B2_DB_NAME=i2b2medcosrv1
      - I2B2_DOMAIN_NAME=i2b2medcosrv1
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8091:8080"
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.110

  medco-unlynx-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    environment:
      - MEDCO_NODE_IDX=1
      - UNLYNX_DEBUG_LEVEL=3
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.111
    volumes:
      - ./configuration:/medco-configuration

  medco-unlynx-wstunnel-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx-wstunnel
    environment:
      - SERVER_LISTEN_URL=ws://0.0.0.0:2003
      - SERVER_DEST_ADDRESS=medco-unlynx-srv1:2003
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.113
    volumes:
      - ./configuration:/medco-configuration

  medco-connector-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    ports:
      - "1991:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv1:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv1
      - I2B2_LOGIN_USER=e2etest
      - I2B2_LOGIN_PASSWORD=e2etest
      - LOG_LEVEL=5
      - MEDCO_NODE_IDX=1
      - MC_DB_NAME=medcoconnectorsrv1
      - I2B2_DB_NAME=i2b2medcosrv1
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.112
    volumes:
      - ./configuration:/medco-configuration

  i2b2-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - I2B2_DB_NAME=i2b2medcosrv2
      - I2B2_DOMAIN_NAME=i2b2medcosrv2
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8092:8080"
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.120

  medco-unlynx-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    environment:
      - MEDCO_NODE_IDX=2
      - UNLYNX_DEBUG_LEVEL=3
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.121
    volumes:
      - ./configuration:/medco-configuration

  medco-unlynx-wstunnel-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx-wstunnel
    environment:
      - SERVER_LISTEN_URL=ws://0.0.0.0:2003
      - SERVER_DEST_ADDRESS=medco-unlynx-srv2:2005
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.123
    volumes:
      - ./configuration:/medco-configuration

  medco-connector-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    ports:
      - "1992:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv2
      - I2B2_LOGIN_USER=e2etest
      - I2B2_LOGIN_PASSWORD=e2etest
      - LOG_LEVEL=5
      - MEDCO_NODE_IDX=2
      - MC_DB_NAME=medcoconnectorsrv2
      - I2B2_DB_NAME=i2b2medcosrv2
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.122

  medco-unlynx-wstunnel-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx-wstunnel
    environment:
      - SERVER_LISTEN_URL=
      - SERVER_DEST_ADDRESS=
      - CLIENT_000_LISTEN_ADDRESS=0.0.0.0:3000
      - CLIENT_000_WS_SERVER_URL=ws://medco-unlynx-wstunnel-srv0:2003
      - CLIENT_000_WS_SERVER_PATH_PREFIX=""
      - CLIENT_000_DEST_ADDRESS=medco-unlynx-srv0:2001
      - CLIENT_001_LISTEN_ADDRESS=0.0.0.0:3001
      - CLIENT_001_WS_SERVER_URL=ws://medco-unlynx-wstunnel-srv1:2003
      - CLIENT_001_WS_SERVER_PATH_PREFIX=""
      - CLIENT_001_DEST_ADDRESS=medco-unlynx-srv1:2003
      - CLIENT_002_LISTEN_ADDRESS=0.0.0.0:3002
      - CLIENT_002_WS_SERVER_URL=ws://medco-unlynx-wstunnel-srv2:2003
      - CLIENT_002_WS_SERVER_PATH_PREFIX=""
      - CLIENT_002_DEST_ADDRESS=medco-unlynx-srv2:2005
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.205
    volumes:
      - ./configuration:/medco-configuration

  postgresql:
    extends:
      file: ../docker-compose-definitions.yml
      service: postgresql
    ports:
      - "5432:5432"
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.202

  pg-admin:
    extends:
      file: ../docker-compose-definitions.yml
      service: pg-admin
    ports:
      - "81:80"
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.203

  keycloak:
    extends:
      file: ../docker-compose-definitions.yml
      service: keycloak
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    networks:
      inter-nodes:
        ipv4_address: 172.31.0.204

networks:
  inter-nodes:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

volumes:
  medcodb:
