version: '2.4'
services:
  medco-cli-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-cli-client
    environment:
      - OIDC_REQ_TOKEN_URL=https://${MEDCO_NODE_HOST:?}/auth/realms/master/protocol/openid-connect/token
      - MEDCO_CONNECTOR_URL=https://${MEDCO_NODE_HOST:?}/local-3nodes/medco-0
      - LOG_LEVEL=${CLICLIENT_LOGLEVEL:?}
    volumes:
      - ./configuration:/medco-configuration

  medco-loader-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - LOG_LEVEL=${LOADER_LOGLEVEL:?}
      - I2B2_DB_NAME=i2b2medcosrv0
      - I2B2_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - MC_DB_NAME=medcoconnectorsrv0
      - MC_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - MEDCO_NODE_IDX=0
    volumes:
      - ./configuration:/medco-configuration
    networks:
      inter-nodes:

  medco-loader-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - LOG_LEVEL=${LOADER_LOGLEVEL:?}
      - I2B2_DB_NAME=i2b2medcosrv1
      - I2B2_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - MC_DB_NAME=medcoconnectorsrv1
      - MC_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - MEDCO_NODE_IDX=1
    volumes:
      - ./configuration:/medco-configuration
    networks:
      inter-nodes:

  medco-loader-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - LOG_LEVEL=${LOADER_LOGLEVEL:?}
      - I2B2_DB_NAME=i2b2medcosrv2
      - I2B2_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - MC_DB_NAME=medcoconnectorsrv2
      - MC_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - MEDCO_NODE_IDX=2
    volumes:
      - ./configuration:/medco-configuration
    networks:
      inter-nodes:

networks:
  inter-nodes:
    external:
      name: dev-local-3nodes_inter-nodes
