// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi MedCo Connector
This is the API of the MedCo connector, that orchestrates the query at the MedCo node. It implements the PIC-SURE 2 API.


    Schemes:
      http
    Host: localhost
    BasePath: /medco
    Version: 0.2.0
    License: EULA https://raw.githubusercontent.com/lca1/medco-connector/master/LICENSE
    Contact: <medco-dev@listes.epfl.ch>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
