version: '2.4'
services:
  medco-cli-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-cli-client
    environment:
      - OIDC_REQ_TOKEN_URL=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/auth/realms/master/protocol/openid-connect/token
      - MEDCO_CONNECTOR_URL=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-0
    volumes:
      - ./configuration:/medco-configuration

  medco-loader-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - I2B2_DB_NAME=i2b2medcosrv0
      - MC_DB_NAME=medcoconnectorsrv0
      - MEDCO_NODE_IDX=0
      - I2B2_DB_HOST=${MEDCO_NODE_HOST:?}
      - MC_DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ./configuration:/medco-configuration

  medco-loader-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - I2B2_DB_NAME=i2b2medcosrv1
      - MC_DB_NAME=medcoconnectorsrv1
      - MEDCO_NODE_IDX=1
      - I2B2_DB_HOST=${MEDCO_NODE_HOST:?}
      - MC_DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ./configuration:/medco-configuration

  medco-loader-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - I2B2_DB_NAME=i2b2medcosrv2
      - MC_DB_NAME=medcoconnectorsrv2
      - MEDCO_NODE_IDX=2
      - I2B2_DB_HOST=${MEDCO_NODE_HOST:?}
      - MC_DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ./configuration:/medco-configuration
