version: "2.4"
services:
  i2b2-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - I2B2_DB_NAME=i2b2medcosrv0
      - I2B2_DOMAIN_NAME=i2b2medcosrv0
      - WILDFLY_ADMIN_PASSWORD=${I2B2_WILDFLY_PASSWORD:?}
      - I2B2_SERVICE_PASSWORD=${I2B2_SERVICE_PASSWORD:?}
      - DEFAULT_USER_PASSWORD=${I2B2_USER_PASSWORD:?}
    ports:
      - "8090:8080"
    networks:
      intra-node-srv0:
        aliases:
          - i2b2
      inter-nodes:

  medco-unlynx-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    ports:
      - "2001:2001"
      - "2002:2002"
    environment:
      - MEDCO_NODE_IDX=0
    networks:
      intra-node-srv0:
      inter-nodes:
        ipv4_address: 172.31.1.101
    volumes:
      - ./configuration:/medco-configuration

  medco-connector-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    ports:
      - "1990:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv0:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv0
      - MEDCO_NODE_IDX=0
      - OIDC_JWT_ISSUERS=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/auth/realms/master
      - I2B2_LOGIN_PASSWORD=${I2B2_USER_PASSWORD:?}
      - MC_DB_NAME=medcoconnectorsrv0
      - I2B2_DB_NAME=i2b2medcosrv0
      - "MEDCO_NODES_URL=\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-0,\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-1,\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-2"
    networks:
      intra-node-srv0:
      inter-nodes:
    volumes:
      - ./configuration:/medco-configuration

  i2b2-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - I2B2_DB_NAME=i2b2medcosrv1
      - I2B2_DOMAIN_NAME=i2b2medcosrv1
      - WILDFLY_ADMIN_PASSWORD=${I2B2_WILDFLY_PASSWORD:?}
      - I2B2_SERVICE_PASSWORD=${I2B2_SERVICE_PASSWORD:?}
      - DEFAULT_USER_PASSWORD=${I2B2_USER_PASSWORD:?}
    ports:
      - "8091:8080"
    networks:
      intra-node-srv1:
        aliases:
          - i2b2
      inter-nodes:

  medco-unlynx-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    ports:
      - "2003:2003"
      - "2004:2004"
    environment:
      - MEDCO_NODE_IDX=1
    networks:
      intra-node-srv1:
      inter-nodes:
        ipv4_address: 172.31.1.111
    volumes:
      - ./configuration:/medco-configuration

  medco-connector-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    ports:
      - "1991:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv1:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv1
      - MEDCO_NODE_IDX=1
      - OIDC_JWT_ISSUERS=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/auth/realms/master
      - I2B2_LOGIN_PASSWORD=${I2B2_USER_PASSWORD:?}
      - MC_DB_NAME=medcoconnectorsrv1
      - I2B2_DB_NAME=i2b2medcosrv1
      - "MEDCO_NODES_URL=\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-0,\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-1,\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-2"
    networks:
      intra-node-srv1:
      inter-nodes:
    volumes:
      - ./configuration:/medco-configuration

  i2b2-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - I2B2_DB_NAME=i2b2medcosrv2
      - I2B2_DOMAIN_NAME=i2b2medcosrv2
      - WILDFLY_ADMIN_PASSWORD=${I2B2_WILDFLY_PASSWORD:?}
      - I2B2_SERVICE_PASSWORD=${I2B2_SERVICE_PASSWORD:?}
      - DEFAULT_USER_PASSWORD=${I2B2_USER_PASSWORD:?}
    ports:
      - "8092:8080"
    networks:
      intra-node-srv2:
        aliases:
          - i2b2
      inter-nodes:

  medco-unlynx-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    ports:
      - "2005:2005"
      - "2006:2006"
    environment:
      - MEDCO_NODE_IDX=2
    networks:
      intra-node-srv2:
      inter-nodes:
        ipv4_address: 172.31.1.121
    volumes:
      - ./configuration:/medco-configuration

  medco-connector-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    ports:
      - "1992:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv2
      - MEDCO_NODE_IDX=2
      - OIDC_JWT_ISSUERS=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/auth/realms/master
      - I2B2_LOGIN_PASSWORD=${I2B2_USER_PASSWORD:?}
      - MC_DB_NAME=medcoconnectorsrv2
      - I2B2_DB_NAME=i2b2medcosrv2
      - "MEDCO_NODES_URL=\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-0,\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-1,\
        ${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-2"
    networks:
      intra-node-srv2:
      inter-nodes:
    volumes:
      - ./configuration:/medco-configuration

  glowing-bear-medco:
    extends:
      file: ../docker-compose-definitions.yml
      service: glowing-bear-medco
    ports:
      - "82:80"
    environment:
      - GB_MEDCO_NODE_URL=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/local-3nodes/medco-0
      - GB_KEYCLOAK_URL=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/auth
      - GB_FOOTER_TEXT=
    networks:
      inter-nodes:

  nginx:
    extends:
      file: ../docker-compose-definitions.yml
      service: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTP_SCHEME=${MEDCO_NODE_HTTP_SCHEME:?}
    networks:
      intra-node-srv0:
      inter-nodes:
    volumes:
      - ./configuration/certificate.crt:/medco-configuration/certificate.crt
      - ./configuration/certificate.key:/medco-configuration/certificate.key

  postgresql:
    extends:
      file: ../docker-compose-definitions.yml
      service: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    networks:
      inter-nodes:

  pg-admin:
    extends:
      file: ../docker-compose-definitions.yml
      service: pg-admin
    ports:
      - "81:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:?}
    networks:
      inter-nodes:

  keycloak:
    extends:
      file: ../docker-compose-definitions.yml
      service: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD:?}
    depends_on:
      - postgresql
    networks:
      inter-nodes:

networks:
  inter-nodes:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.1.0/24

  intra-node-srv0:
    driver: bridge
  intra-node-srv1:
    driver: bridge
  intra-node-srv2:
    driver: bridge

volumes:
  medcodb:
