// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ExploreSearchModifierOKCode is the HTTP code returned for type ExploreSearchModifierOK
const ExploreSearchModifierOKCode int = 200

/*ExploreSearchModifierOK MedCo-Explore search modifier query response.

swagger:response exploreSearchModifierOK
*/
type ExploreSearchModifierOK struct {

	/*
	  In: Body
	*/
	Payload *ExploreSearchModifierOKBody `json:"body,omitempty"`
}

// NewExploreSearchModifierOK creates ExploreSearchModifierOK with default headers values
func NewExploreSearchModifierOK() *ExploreSearchModifierOK {

	return &ExploreSearchModifierOK{}
}

// WithPayload adds the payload to the explore search modifier o k response
func (o *ExploreSearchModifierOK) WithPayload(payload *ExploreSearchModifierOKBody) *ExploreSearchModifierOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore search modifier o k response
func (o *ExploreSearchModifierOK) SetPayload(payload *ExploreSearchModifierOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreSearchModifierOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ExploreSearchModifierDefault Error response.

swagger:response exploreSearchModifierDefault
*/
type ExploreSearchModifierDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *ExploreSearchModifierDefaultBody `json:"body,omitempty"`
}

// NewExploreSearchModifierDefault creates ExploreSearchModifierDefault with default headers values
func NewExploreSearchModifierDefault(code int) *ExploreSearchModifierDefault {
	if code <= 0 {
		code = 500
	}

	return &ExploreSearchModifierDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the explore search modifier default response
func (o *ExploreSearchModifierDefault) WithStatusCode(code int) *ExploreSearchModifierDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the explore search modifier default response
func (o *ExploreSearchModifierDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the explore search modifier default response
func (o *ExploreSearchModifierDefault) WithPayload(payload *ExploreSearchModifierDefaultBody) *ExploreSearchModifierDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore search modifier default response
func (o *ExploreSearchModifierDefault) SetPayload(payload *ExploreSearchModifierDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreSearchModifierDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
