// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ExploreSearchConceptOKCode is the HTTP code returned for type ExploreSearchConceptOK
const ExploreSearchConceptOKCode int = 200

/*ExploreSearchConceptOK MedCo-Explore search concept query response.

swagger:response exploreSearchConceptOK
*/
type ExploreSearchConceptOK struct {

	/*
	  In: Body
	*/
	Payload *ExploreSearchConceptOKBody `json:"body,omitempty"`
}

// NewExploreSearchConceptOK creates ExploreSearchConceptOK with default headers values
func NewExploreSearchConceptOK() *ExploreSearchConceptOK {

	return &ExploreSearchConceptOK{}
}

// WithPayload adds the payload to the explore search concept o k response
func (o *ExploreSearchConceptOK) WithPayload(payload *ExploreSearchConceptOKBody) *ExploreSearchConceptOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore search concept o k response
func (o *ExploreSearchConceptOK) SetPayload(payload *ExploreSearchConceptOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreSearchConceptOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ExploreSearchConceptDefault Error response.

swagger:response exploreSearchConceptDefault
*/
type ExploreSearchConceptDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *ExploreSearchConceptDefaultBody `json:"body,omitempty"`
}

// NewExploreSearchConceptDefault creates ExploreSearchConceptDefault with default headers values
func NewExploreSearchConceptDefault(code int) *ExploreSearchConceptDefault {
	if code <= 0 {
		code = 500
	}

	return &ExploreSearchConceptDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the explore search concept default response
func (o *ExploreSearchConceptDefault) WithStatusCode(code int) *ExploreSearchConceptDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the explore search concept default response
func (o *ExploreSearchConceptDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the explore search concept default response
func (o *ExploreSearchConceptDefault) WithPayload(payload *ExploreSearchConceptDefaultBody) *ExploreSearchConceptDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the explore search concept default response
func (o *ExploreSearchConceptDefault) SetPayload(payload *ExploreSearchConceptDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExploreSearchConceptDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
