version: "2.4"
services:
  i2b2:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - WILDFLY_ADMIN_PASSWORD=${I2B2_WILDFLY_PASSWORD:?}
      - I2B2_SERVICE_PASSWORD=${I2B2_SERVICE_PASSWORD:?}
      - DEFAULT_USER_PASSWORD=${I2B2_USER_PASSWORD:?}
    networks:
      - medco-network

  medco-unlynx:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    environment:
      - MEDCO_NODE_IDX=${MEDCO_NODE_IDX:?}
    ports:
      - "2001:2001"
    volumes:
      - ./configuration:/medco-configuration
    networks:
      - medco-network

  medco-connector:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    environment:
      - MEDCO_NODE_IDX=${MEDCO_NODE_IDX:?}
      - I2B2_LOGIN_PASSWORD=${I2B2_USER_PASSWORD:?}
      - OIDC_JWKS_URLS=${OIDC_JWKS_URLS:?}
      - OIDC_JWT_ISSUERS=${OIDC_JWT_ISSUERS:?}
      - OIDC_CLIENT_IDS=${OIDC_CLIENT_IDS:?}
      - OIDC_JWT_USER_ID_CLAIMS=${OIDC_JWT_USER_ID_CLAIMS:?}
      - MEDCO_NODES_URL=${MEDCO_NODES_URL:?}
    volumes:
      - ./configuration:/medco-configuration
    networks:
      - medco-network

  glowing-bear-medco:
    extends:
      file: ../docker-compose-definitions.yml
      service: glowing-bear-medco
    environment:
      - GB_MEDCO_NODE_URL=https://${MEDCO_NODE_DNS_NAME:?}/medco
      - GB_KEYCLOAK_URL=https://${MEDCO_NODE_DNS_NAME:?}/auth
      - GB_KEYCLOAK_REALM=${KEYCLOAK_REALM:?}
      - GB_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:?}
      - GB_FOOTER_TEXT=MedCo network ${MEDCO_NETWORK_NAME:?}, node ${MEDCO_NODE_IDX:?} / ${MEDCO_NODE_DNS_NAME:?}
    networks:
      - medco-network

  nginx:
    extends:
      file: ../docker-compose-definitions.yml
      service: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTP_SCHEME=https
      - PROD_CONFIG=true
    volumes:
      - ./configuration/group.toml:/medco-configuration/group.toml
      - ./configuration/certificate.crt:/medco-configuration/certificate.crt
      - ./configuration/certificate.key:/medco-configuration/certificate.key
    networks:
      - medco-network

  postgresql:
    extends:
      file: ../docker-compose-definitions.yml
      service: postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    ports:
      - "5432:5432"
    networks:
      - medco-network

  keycloak:
    extends:
      file: ../docker-compose-definitions.yml
      service: keycloak
    environment:
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD:?}
    depends_on:
      - postgresql
    networks:
      - medco-network

volumes:
  medcodb:

networks:
  medco-network:
    driver: bridge
