version: "2.4"
services:
  i2b2:
    extends:
      file: ../docker-compose-definitions.yml
      service: i2b2
    environment:
      - WILDFLY_ADMIN_PASSWORD=${I2B2_WILDFLY_PASSWORD:?}
      - I2B2_SERVICE_PASSWORD=${I2B2_SERVICE_PASSWORD:?}
      - DEFAULT_USER_PASSWORD=${I2B2_USER_PASSWORD:?}
      - I2B2_DB_PW=${DB_ALL_USERS_PASSWORD:?}
      - AXIS2_LOGLEVEL=${I2B2_LOGLEVEL:?}

  medco-unlynx:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx
    environment:
      - MEDCO_NODE_IDX=${MEDCO_NODE_IDX:?}
      - UNLYNX_DEBUG_LEVEL=${UNLYNX_LOGLEVEL:?}
    volumes:
      - ./configuration:/medco-configuration

  medco-unlynx-wstunnel:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-unlynx-wstunnel
    environment:
      - SERVER_LISTEN_URL=ws://0.0.0.0:2003
      - SERVER_DEST_ADDRESS=medco-unlynx:2001
      - CLIENTS_LISTEN_ADDRESSES=${WS_CLIENTS_LISTEN_ADDRESSES:?}
      - CLIENTS_WS_SERVER_URLS=${WS_CLIENTS_WS_SERVER_URLS:?}
      - CLIENTS_WS_SERVER_PATH_PREFIXES=${WS_CLIENTS_WS_SERVER_PATH_PREFIXES:?}
      - CLIENTS_DEST_ADDRESSES=${WS_CLIENTS_DEST_ADDRESSES:?}
    volumes:
      - ./configuration:/medco-configuration

  medco-connector:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-connector
    environment:
      - MEDCO_NODE_IDX=${MEDCO_NODE_IDX:?}
      - I2B2_LOGIN_PASSWORD=${I2B2_USER_PASSWORD:?}
      - OIDC_JWKS_URLS=${OIDC_JWKS_URLS:?}
      - OIDC_JWT_ISSUERS=${OIDC_JWT_ISSUERS:?}
      - OIDC_CLIENT_IDS=${OIDC_CLIENT_IDS:?}
      - OIDC_JWT_USER_ID_CLAIMS=${OIDC_JWT_USER_ID_CLAIMS:?}
      - MEDCO_NODES_URL=${MEDCO_NODES_URL:?}
      - MC_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - I2B2_DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
      - LOG_LEVEL=${CONNECTOR_LOGLEVEL:?}
    volumes:
      - ./configuration:/medco-configuration

  glowing-bear-medco:
    extends:
      file: ../docker-compose-definitions.yml
      service: glowing-bear-medco
    environment:
      - GB_MEDCO_NODE_URL=https://${MEDCO_NODE_DNS_NAME:?}/medco
      - GB_KEYCLOAK_URL=https://${MEDCO_NODE_DNS_NAME:?}/auth
      - GB_KEYCLOAK_REALM=${KEYCLOAK_REALM:?}
      - GB_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:?}
      - GB_FOOTER_TEXT=MedCo network ${MEDCO_NETWORK_NAME:?}, node ${MEDCO_NODE_IDX:?} / ${MEDCO_NODE_DNS_NAME:?}

  nginx:
    extends:
      file: ../docker-compose-definitions.yml
      service: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PROD_CONFIG=true
    volumes:
      - ./configuration/certificate.crt:/medco-configuration/certificate.crt
      - ./configuration/certificate.key:/medco-configuration/certificate.key

  postgresql:
    extends:
      file: ../docker-compose-definitions.yml
      service: postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - DB_ALL_USERS_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
    ports:
      - "5432:5432"

  keycloak:
    extends:
      file: ../docker-compose-definitions.yml
      service: keycloak
    environment:
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD:?}
      - DB_PASSWORD=${DB_ALL_USERS_PASSWORD:?}
    depends_on:
      - postgresql

volumes:
  medcodb:
