// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// RestAPIAuthorization rest Api authorization
//
// swagger:model restApiAuthorization
type RestAPIAuthorization string

const (

	// RestAPIAuthorizationMedcoDashNetwork captures enum value "medco-network"
	RestAPIAuthorizationMedcoDashNetwork RestAPIAuthorization = "medco-network"

	// RestAPIAuthorizationMedcoDashExplore captures enum value "medco-explore"
	RestAPIAuthorizationMedcoDashExplore RestAPIAuthorization = "medco-explore"

	// RestAPIAuthorizationMedcoDashGenomicDashAnnotations captures enum value "medco-genomic-annotations"
	RestAPIAuthorizationMedcoDashGenomicDashAnnotations RestAPIAuthorization = "medco-genomic-annotations"

	// RestAPIAuthorizationMedcoDashSurvivalDashAnalysis captures enum value "medco-survival-analysis"
	RestAPIAuthorizationMedcoDashSurvivalDashAnalysis RestAPIAuthorization = "medco-survival-analysis"
)

// for schema
var restApiAuthorizationEnum []interface{}

func init() {
	var res []RestAPIAuthorization
	if err := json.Unmarshal([]byte(`["medco-network","medco-explore","medco-genomic-annotations","medco-survival-analysis"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		restApiAuthorizationEnum = append(restApiAuthorizationEnum, v)
	}
}

func (m RestAPIAuthorization) validateRestAPIAuthorizationEnum(path, location string, value RestAPIAuthorization) error {
	if err := validate.EnumCase(path, location, value, restApiAuthorizationEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this rest Api authorization
func (m RestAPIAuthorization) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRestAPIAuthorizationEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this rest Api authorization based on context it is used
func (m RestAPIAuthorization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
