// Code generated by go-swagger; DO NOT EDIT.

package picsure2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/lca1/medco-connector/swagger/models"
)

// QuerySyncOKCode is the HTTP code returned for type QuerySyncOK
const QuerySyncOKCode int = 200

/*QuerySyncOK Query result.

swagger:response querySyncOK
*/
type QuerySyncOK struct {

	/*
	  In: Body
	*/
	Payload models.QueryResult `json:"body,omitempty"`
}

// NewQuerySyncOK creates QuerySyncOK with default headers values
func NewQuerySyncOK() *QuerySyncOK {

	return &QuerySyncOK{}
}

// WithPayload adds the payload to the query sync o k response
func (o *QuerySyncOK) WithPayload(payload models.QueryResult) *QuerySyncOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the query sync o k response
func (o *QuerySyncOK) SetPayload(payload models.QueryResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *QuerySyncOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
