// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ldsec/medco-connector/restapi/models"
)

// NewExploreSearchParams creates a new ExploreSearchParams object
// with the default values initialized.
func NewExploreSearchParams() *ExploreSearchParams {
	var ()
	return &ExploreSearchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExploreSearchParamsWithTimeout creates a new ExploreSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExploreSearchParamsWithTimeout(timeout time.Duration) *ExploreSearchParams {
	var ()
	return &ExploreSearchParams{

		timeout: timeout,
	}
}

// NewExploreSearchParamsWithContext creates a new ExploreSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewExploreSearchParamsWithContext(ctx context.Context) *ExploreSearchParams {
	var ()
	return &ExploreSearchParams{

		Context: ctx,
	}
}

// NewExploreSearchParamsWithHTTPClient creates a new ExploreSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExploreSearchParamsWithHTTPClient(client *http.Client) *ExploreSearchParams {
	var ()
	return &ExploreSearchParams{
		HTTPClient: client,
	}
}

/*ExploreSearchParams contains all the parameters to send to the API endpoint
for the explore search operation typically these are written to a http.Request
*/
type ExploreSearchParams struct {

	/*SearchRequest
	  MedCo-Explore ontology search request.

	*/
	SearchRequest *models.ExploreSearch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the explore search params
func (o *ExploreSearchParams) WithTimeout(timeout time.Duration) *ExploreSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the explore search params
func (o *ExploreSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the explore search params
func (o *ExploreSearchParams) WithContext(ctx context.Context) *ExploreSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the explore search params
func (o *ExploreSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the explore search params
func (o *ExploreSearchParams) WithHTTPClient(client *http.Client) *ExploreSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the explore search params
func (o *ExploreSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSearchRequest adds the searchRequest to the explore search params
func (o *ExploreSearchParams) WithSearchRequest(searchRequest *models.ExploreSearch) *ExploreSearchParams {
	o.SetSearchRequest(searchRequest)
	return o
}

// SetSearchRequest adds the searchRequest to the explore search params
func (o *ExploreSearchParams) SetSearchRequest(searchRequest *models.ExploreSearch) {
	o.SearchRequest = searchRequest
}

// WriteToRequest writes these params to a swagger request
func (o *ExploreSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SearchRequest != nil {
		if err := r.SetBodyParam(o.SearchRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
