// Code generated by go-swagger; DO NOT EDIT.

package medco_node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutDefaultCohortParams creates a new PutDefaultCohortParams object
// with the default values initialized.
func NewPutDefaultCohortParams() *PutDefaultCohortParams {
	var ()
	return &PutDefaultCohortParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutDefaultCohortParamsWithTimeout creates a new PutDefaultCohortParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutDefaultCohortParamsWithTimeout(timeout time.Duration) *PutDefaultCohortParams {
	var ()
	return &PutDefaultCohortParams{

		timeout: timeout,
	}
}

// NewPutDefaultCohortParamsWithContext creates a new PutDefaultCohortParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutDefaultCohortParamsWithContext(ctx context.Context) *PutDefaultCohortParams {
	var ()
	return &PutDefaultCohortParams{

		Context: ctx,
	}
}

// NewPutDefaultCohortParamsWithHTTPClient creates a new PutDefaultCohortParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutDefaultCohortParamsWithHTTPClient(client *http.Client) *PutDefaultCohortParams {
	var ()
	return &PutDefaultCohortParams{
		HTTPClient: client,
	}
}

/*PutDefaultCohortParams contains all the parameters to send to the API endpoint
for the put default cohort operation typically these are written to a http.Request
*/
type PutDefaultCohortParams struct {

	/*Name
	  Name of the cohort to set as the new default cohort

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put default cohort params
func (o *PutDefaultCohortParams) WithTimeout(timeout time.Duration) *PutDefaultCohortParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put default cohort params
func (o *PutDefaultCohortParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put default cohort params
func (o *PutDefaultCohortParams) WithContext(ctx context.Context) *PutDefaultCohortParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put default cohort params
func (o *PutDefaultCohortParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put default cohort params
func (o *PutDefaultCohortParams) WithHTTPClient(client *http.Client) *PutDefaultCohortParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put default cohort params
func (o *PutDefaultCohortParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the put default cohort params
func (o *PutDefaultCohortParams) WithName(name string) *PutDefaultCohortParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put default cohort params
func (o *PutDefaultCohortParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutDefaultCohortParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
